# Generated by Django 3.1.7 on 2021-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('profilepicture', models.ImageField(upload_to='compressor')),
                ('phonenumber', models.BigIntegerField(null=True)),
                ('emailid', models.EmailField(max_length=200)),
            ],
        ),
    ]
