# Generated by Django 3.1.7 on 2021-03-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webletter_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('theme_image', models.ImageField(null=True, upload_to='themes_compressor')),
                ('article', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogusers',
            name='emailid',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogusers',
            name='profilepicture',
            field=models.ImageField(null=True, upload_to='compressor'),
        ),
    ]
