# Generated by Django 3.1.7 on 2021-03-23 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webletter_api', '0002_auto_20210323_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webletter_api.blogusers'),
        ),
    ]
