# Generated by Django 3.1.7 on 2021-04-05 05:40

from django.db import migrations, models
import webletter_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('webletter_api', '0005_auto_20210325_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogusers',
            name='profilepicture',
            field=models.ImageField(blank=True, default='/pp/default/blank.jpeg', null=True, upload_to=webletter_api.models.profilePictureUpload),
        ),
    ]
