# Generated by Django 3.1.7 on 2021-04-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webletter_api', '0006_auto_20210405_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('userdata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webletter_api.blogusers')),
            ],
        ),
    ]
